Improve CI script logging

diff --git a/ci/android-wait-for-emulator b/ci/android-wait-for-emulator
--- a/ci/android-wait-for-emulator
+++ b/ci/android-wait-for-emulator
@@ -1,8 +1,8 @@
 #!/bin/bash
 # Copied from https://github.com/travis-ci/travis-cookbooks/blob/precise-stable/ci_environment/android-sdk/files/default/android-wait-for-emulator which is released under the MIT license.
 
-# Print executed commands; fail fast when a command returns non-zero exit code.
-set -ev
+# Fail fast when a command returns non-zero exit code.
+set -e
 
 bootanim=""
 failcounter=0
@@ -13,13 +13,13 @@ until [[ "$bootanim" =~ "stopped" ]]; do
   if [[ "$bootanim" =~ "device not found" || "$bootanim" =~ "device offline"
     || "$bootanim" =~ "running" ]]; then
     let "failcounter += 1"
-    echo "Waiting for emulator to start"
+    echo "Waiting for emulator to start."
     if [[ $failcounter -gt timeout_in_sec ]]; then
-      echo "Timeout ($timeout_in_sec seconds) reached; failed to start emulator"
+      echo "Timeout ($timeout_in_sec seconds) reached. Failed to start emulator."
       exit 1
     fi
   fi
   sleep 1
 done
 
-echo "Emulator is ready"
+echo "Emulator is ready."
diff --git a/ci/assemble b/ci/assemble
--- a/ci/assemble
+++ b/ci/assemble
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 
-# Print executed commands; fail fast when a command returns non-zero exit code.
-set -ev
+# Fail fast when a command returns non-zero exit code.
+set -e
 
+echo "Assembling project with Gradle."
 ./gradlew --console=plain assemble
diff --git a/ci/install-emulator b/ci/install-emulator
--- a/ci/install-emulator
+++ b/ci/install-emulator
@@ -1,11 +1,13 @@
 #!/usr/bin/env bash
 
-# Print executed commands; fail fast when a command returns non-zero exit code.
-set -ev
+# Fail fast when a command returns non-zero exit code.
+set -e
 
 # Download emulator.
+echo "Installing Android emulator."
 silent-sdkmanager "emulator"
 # Download system image.
+echo "Installing system image for Android SDK $EMULATOR_ANDROID_SDK (ABI: $EMULATOR_ABI)."
 silent-sdkmanager "system-images;android-$EMULATOR_ANDROID_SDK;google_apis;$EMULATOR_ABI"
 
 update-sdk
diff --git a/ci/install-sdk b/ci/install-sdk
--- a/ci/install-sdk
+++ b/ci/install-sdk
@@ -1,7 +1,10 @@
 #!/usr/bin/env bash
 
-# Print executed commands; fail fast when a command returns non-zero exit code.
-set -ev
+# Fail fast when a command returns non-zero exit code.
+set -e
+
+SDK_DOWNLOAD_URL="https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip"
+
 
 # Fix missing config file.
 touch ~/.android/repositories.cfg
@@ -10,15 +13,19 @@ touch ~/.android/repositories.cfg
 # Download and unzip Android SDK tools (if not already cached)
 # Latest version available here: https://developer.android.com/studio/#command-tools
 SDK_DOWNLOAD_DIR="$ANDROID_HOME/tmp/dl"
+SDK_DOWNLOAD_ZIP="$SDK_DOWNLOAD_DIR/sdk-tools.zip"
 mkdir -p ${SDK_DOWNLOAD_DIR}
-if test ! -e "$SDK_DOWNLOAD_DIR/sdk-tools.zip"
+if test ! -e ${SDK_DOWNLOAD_ZIP}
 then
-    curl "https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip" > "$SDK_DOWNLOAD_DIR/sdk-tools.zip"
+    echo "Downloading SDK tools from $SDK_DOWNLOAD_URL to $SDK_DOWNLOAD_ZIP."
+    curl ${SDK_DOWNLOAD_URL} > ${SDK_DOWNLOAD_ZIP}
 fi
-unzip -qq -n "$SDK_DOWNLOAD_DIR/sdk-tools.zip" -d ${ANDROID_HOME}
+echo "Unzipping $SDK_DOWNLOAD_ZIP."
+unzip -qq -n ${SDK_DOWNLOAD_ZIP} -d ${ANDROID_HOME}
 
 
 # Download SDK tools.
+echo "Installing SDK tools."
 silent-sdkmanager "tools"
 silent-sdkmanager "build-tools;$ANDROID_BUILD_TOOLS"
 silent-sdkmanager "platform-tools"
diff --git a/ci/integration-tests b/ci/integration-tests
--- a/ci/integration-tests
+++ b/ci/integration-tests
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
-# Print executed commands; fail fast when a command returns non-zero exit code.
-set -ev
+# Fail fast when a command returns non-zero exit code.
+set -e
 
 install-emulator
 launch-emulator
@@ -9,6 +9,7 @@ launch-emulator
 # Generate code coverage tests.
 # (`travis_wait` is needed because Travis kills the build after 10 minutes without log output:
 # https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received)
+echo "Running connected instrumentation tests with Gradle."
 travis_wait 20 ./gradlew --console=plain connectedCheck
 # TODO Instead of using `connectedCheck`, run integration tests on multiple devices using Spoon:
 #travis_wait 20 ./gradlew --console=plain spoonDebugAndroidTest
diff --git a/ci/launch-emulator b/ci/launch-emulator
--- a/ci/launch-emulator
+++ b/ci/launch-emulator
@@ -1,18 +1,25 @@
 #!/usr/bin/env bash
 
-# Print executed commands; fail fast when a command returns non-zero exit code.
-set -ev
+# Fail fast when a command returns non-zero exit code.
+set -e
+
 
 sdk=${EMULATOR_ANDROID_SDK}
 abi=${EMULATOR_ABI}
 
 # Create and start emulator.
+echo "Creating emulator device running SDK $sdk on $abi."
 echo no | avdmanager create avd \
     --force -c 200M -n "test-$sdk-$abi" -k "system-images;android-$sdk;default;$abi"
+echo "Starting emulator device."
 emulator -avd "test-$sdk-$abi" -no-audio -no-window &
+
 
 # Wait for AVD to start.
 android-wait-for-emulator
+
+
+echo "Transferring emulator configuration."
 
 # Turn off animations.
 adb shell settings put global window_animation_scale 0 &
@@ -24,5 +31,7 @@ adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
 adb shell stop installd
 adb shell start installd
 
+
 # Wake up device.
+echo "Wake up emulator."
 adb shell input keyevent 82 &
diff --git a/ci/test-coverage b/ci/test-coverage
--- a/ci/test-coverage
+++ b/ci/test-coverage
@@ -1,10 +1,12 @@
 #!/usr/bin/env bash
 
-# Print executed commands; fail fast when a command returns non-zero exit code.
-set -ev
+# Fail fast when a command returns non-zero exit code.
+set -e
 
 # Set up code coverage report
+echo "Setting up code coverage report with Gradle."
 ./gradlew --console=plain jacocoTestReport
 
 # Upload code coverage report
+echo "Uploading report to 'https://codecov.io/'."
 curl -s https://codecov.io/bash | bash -
diff --git a/ci/update-sdk b/ci/update-sdk
--- a/ci/update-sdk
+++ b/ci/update-sdk
@@ -1,9 +1,12 @@
 #!/usr/bin/env bash
 
-# Print executed commands; fail fast when a command returns non-zero exit code.
-set -ev
+# Fail fast when a command returns non-zero exit code.
+set -e
 
 # Update SDK dependencies.
+echo "Updating Android SDK components."
 silent-sdkmanager --update
+
 # Accept licenses.
+echo "Accepting all Android SDK licenses."
 silent-sdkmanager --licenses
